# Generated by Django 2.2.2 on 2019-06-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0004_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='league',
        ),
    ]
