# Generated by Django 2.2.2 on 2019-06-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0005_remove_game_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Leagues.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_requests_created', to='Leagues.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_requests_createdd', to='Leagues.Team'),
        ),
    ]
