# Generated by Django 2.2.2 on 2019-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0008_auto_20190625_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='league',
        ),
        migrations.AlterField(
            model_name='division',
            name='abbreviation',
            field=models.CharField(max_length=2),
        ),
    ]
