# Generated by Django 2.2.2 on 2019-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0009_auto_20190625_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
