# Generated by Django 2.2.2 on 2019-06-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0010_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Leagues.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Leagues.Game'),
        ),
        migrations.AddField(
            model_name='slot',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
