# Generated by Django 2.2.2 on 2019-06-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0011_auto_20190627_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
