# Generated by Django 2.2.2 on 2019-06-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0012_auto_20190627_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='isScheduled',
            field=models.BooleanField(default=False),
        ),
    ]
